apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports: 
   - targetPort: 80 #optional, if not set, same with port
     port: 80 #mandatory
     nodePort: 30008 #optional, if not set, generate automatic allocation
